name: Run preCICE Tutorials
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths:
      - '**'
      
jobs:  
  run_ht_simple:
    name: Run HT, simple
    runs-on: ubuntu-latest
    container: precice/precice
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2      
      - name: Install Dependencies & FEniCSx
        run: |
          apt-get -qq update
          apt-get -qq install software-properties-common python3-dev python3-pip git apt-utils
          add-apt-repository -y ppa:fenics-packages/fenics
          apt-get -qq install --no-install-recommends fenicsx
          rm -rf /var/lib/apt/lists/*
      - name: Install adapter
        run:  pip3 install --user .
      - name: Get tutorials
        run: git clone -b master https://github.com/PhilipHildebrand/tutorials.git
      - name: Run tutorial
        run: | 
          cd tutorials/partitioned-heat-conduction/fenicsx
          ./run.sh -d & ./run.sh -n
